import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/formatting/Header";
import Footer from "../components/formatting/Footer";
import { cookies } from "next/headers"; // Next.js API to get cookies
import { SessionProvider } from "../components/formatting/SessionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Extract cookies on the server side
  const sessionCookie = cookies().get("session_token");

  // Get the session token from the cookie (if it exists)
  const session = sessionCookie ? { token: sessionCookie.value } : null;

  return (
    <html>
      <head>
        <title>chessGambit</title>
      </head>
      <SessionProvider session={session}>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </SessionProvider>
    </html>
  );
}
