services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Expose port 80 for HTTP traffic
      - "443:443" # Expose port 443 for HTTPS traffic (if needed)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount custom NGINX config file
      - ./certs:/etc/nginx/certs # Mount SSL certificates for HTTPS
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  db-data:
