FROM node:20.11.1 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .


FROM node:20.11.1-slim
WORKDIR /app
COPY --from=builder /app /app

EXPOSE 3001


CMD ["node", "src/server.js"]
