apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chessgambit-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "" # Leave blank for IP-based routing or set to a domain when ready
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
