apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"cert-manager-startupapicheck"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"cert-manager-startupapicheck"}]},"modified":true}'
    autopilot.gke.io/warden-version: 3.0.31
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
  creationTimestamp: "2024-09-12T15:20:02Z"
  generation: 1
  labels:
    app: startupapicheck
    app.kubernetes.io/component: startupapicheck
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: startupapicheck
    app.kubernetes.io/version: v1.15.3
    helm.sh/chart: cert-manager-v1.15.3
  name: cert-manager-startupapicheck
  namespace: cert-manager
  resourceVersion: "3359342"
  uid: 72cd5562-142d-466b-8359-5854375e83fc
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 72cd5562-142d-466b-8359-5854375e83fc
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: startupapicheck
        app.kubernetes.io/component: startupapicheck
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: startupapicheck
        app.kubernetes.io/version: v1.15.3
        batch.kubernetes.io/controller-uid: 72cd5562-142d-466b-8359-5854375e83fc
        batch.kubernetes.io/job-name: cert-manager-startupapicheck
        controller-uid: 72cd5562-142d-466b-8359-5854375e83fc
        helm.sh/chart: cert-manager-v1.15.3
        job-name: cert-manager-startupapicheck
    spec:
      containers:
        - args:
            - check
            - api
            - --wait=1m
            - -v
          image: quay.io/jetstack/cert-manager-startupapicheck:v1.15.3
          imagePullPolicy: IfNotPresent
          name: cert-manager-startupapicheck
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: cert-manager-startupapicheck
      serviceAccountName: cert-manager-startupapicheck
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
status:
  conditions:
    - lastProbeTime: "2024-09-12T15:27:32Z"
      lastTransitionTime: "2024-09-12T15:27:32Z"
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
  failed: 1
  ready: 1
  startTime: "2024-09-12T15:20:02Z"
  terminating: 0
  uncountedTerminatedPods: {}
